name = "BasinsCollection"
authors = ["Wagemakers"]

[deps]
DiffEqPhysics = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
DrWatson = "2.9.1"
julia = "1.7.2"
